// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title AgeVerifier
 * @dev Zero-knowledge proof verifier for age verification
 * This contract will be auto-generated by circom/snarkjs from the age18 circuit
 */
contract AgeVerifier {
    // This is a placeholder - the actual verifier will be generated by circom
    // The real verifier will contain complex cryptographic operations
    
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[2] memory input
    ) public pure returns (bool) {
        // Placeholder implementation - replace with actual generated verifier
        // The real verifier will verify Groth16 proofs
        
        // Basic validation
        require(a[0] != 0 && a[1] != 0, "Invalid proof component a");
        require(b[0][0] != 0 && b[0][1] != 0, "Invalid proof component b[0]");
        require(b[1][0] != 0 && b[1][1] != 0, "Invalid proof component b[1]");
        require(c[0] != 0 && c[1] != 0, "Invalid proof component c");
        
        // Validate inputs
        require(input[0] >= 18, "Minimum age requirement not met");
        require(input[1] > 0, "Invalid current year");
        
        // In production, this would contain the actual ZK proof verification
        // For now, returning true for demonstration
        return true;
    }
}

/**
 * @title AgeVerificationSystem
 * @dev Main contract for age verification system
 */
contract AgeVerificationSystem {
    AgeVerifier public immutable verifier;
    
    struct UserVerification {
        bool isVerified;
        uint256 commitment;
        uint256 timestamp;
        uint256 minAge;
        uint256 currentYear;
    }
    
    // Events
    event UserVerified(address indexed user, uint256 commitment, uint256 minAge, uint256 currentYear);
    event VerificationRevoked(address indexed user);
    
    // Mappings
    mapping(address => UserVerification) public userVerifications;
    
    // Configuration
    uint256 public constant MIN_AGE_REQUIRED = 18;
    uint256 public constant VERIFICATION_VALIDITY_PERIOD = 365 days;
    
    modifier onlyVerifiedUser() {
        require(isUserVerified(msg.sender), "User not verified or verification expired");
        _;
    }
    
    constructor(address _verifier) {
        verifier = AgeVerifier(_verifier);
    }
    
    /**
     * @dev Submit ZK proof for age verification
     * @param proof The ZK-SNARK proof components [a, b, c]
     * @param publicInputs [minAge, currentYear, publicHash]
     * @param commitment The commitment hash from the proof
     */
    function verifyAge(
        uint[8] memory proof, // [a[0], a[1], b[0][0], b[0][1], b[1][0], b[1][1], c[0], c[1]]
        uint[2] memory publicInputs, // [minAge, currentYear]
        uint256 commitment
    ) external {
        require(publicInputs[0] >= MIN_AGE_REQUIRED, "Minimum age requirement not met");
        require(publicInputs[1] > 0, "Invalid current year");
        
        // Reconstruct proof components
        uint[2] memory a = [proof[0], proof[1]];
        uint[2][2] memory b = [[proof[2], proof[3]], [proof[4], proof[5]]];
        uint[2] memory c = [proof[6], proof[7]];
        
        // Verify the ZK proof
        bool proofValid = verifier.verifyProof(a, b, c, publicInputs);
        require(proofValid, "Invalid zero-knowledge proof");
        
        // Store verification
        userVerifications[msg.sender] = UserVerification({
            isVerified: true,
            commitment: commitment,
            timestamp: block.timestamp,
            minAge: publicInputs[0],
            currentYear: publicInputs[1]
        });
        
        emit UserVerified(msg.sender, commitment, publicInputs[0], publicInputs[1]);
    }
    
    /**
     * @dev Check if user is verified and verification hasn't expired
     */
    function isUserVerified(address user) public view returns (bool) {
        UserVerification memory userVerif = userVerifications[user];
        return userVerif.isVerified && 
               (block.timestamp - userVerif.timestamp) <= VERIFICATION_VALIDITY_PERIOD;
    }
    
    /**
     * @dev Get user verification details
     */
    function getUserVerification(address user) 
        external 
        view 
        returns (
            bool isVerified, 
            uint256 commitment, 
            uint256 timestamp, 
            uint256 minAge,
            uint256 currentYear
        ) 
    {
        UserVerification memory userVerif = userVerifications[user];
        return (
            isUserVerified(user), 
            userVerif.commitment, 
            userVerif.timestamp, 
            userVerif.minAge,
            userVerif.currentYear
        );
    }
    
    /**
     * @dev Revoke verification (admin only)
     */
    function revokeVerification(address user) external {
        // In production, add proper access control (e.g., Ownable)
        require(userVerifications[user].isVerified, "User not verified");
        
        delete userVerifications[user];
        emit VerificationRevoked(user);
    }
    
    /**
     * @dev Check if user can register (age verified)
     */
    function canRegister(address user) external view returns (bool) {
        return isUserVerified(user);
    }
}
